version: "3"

services:
  db: 
    image: postgres
    container_name: rentx-db
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=r6e5n4t3x10000
      - POSTGRES_DB=rentx 
    volumes: 
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: rentx-app
    restart: always
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app 
    links: 
      - db
    depends_on:
      - db

volumes: 
  pgdata: 
    driver: local